/*
 *
 * MyStuffPage constants
 *
 */

export const GET_MY_QUESTIONS = 'app/MyStuffPage/GET_MY_QUESTIONS';
export const GET_MY_QUESTIONS_PENDING = 'app/MyStuffPage/GET_MY_QUESTIONS_PENDING';
export const GET_MY_QUESTIONS_FULFILLED = 'app/MyStuffPage/GET_MY_QUESTIONS_FULFILLED';
export const GET_MY_QUESTIONS_REJECTED = 'app/MyStuffPage/GET_MY_QUESTIONS_REJECTED';

export const GET_MY_ANSWERS = 'app/MyStuffPage/GET_MY_ANSWERS';
export const GET_MY_ANSWERS_PENDING = 'app/MyStuffPage/GET_MY_ANSWERS_PENDING';
export const GET_MY_ANSWERS_FULFILLED = 'app/MyStuffPage/GET_MY_ANSWERS_FULFILLED';
export const GET_MY_ANSWERS_REJECTED = 'app/MyStuffPage/GET_MY_ANSWERS_REJECTED';

export const GET_MY_SUBSCRIPTIONS = 'app/MyStuffPage/GET_MY_SUBSCRIPTIONS';
export const GET_MY_SUBSCRIPTIONS_PENDING = 'app/MyStuffPage/GET_MY_SUBSCRIPTIONS_PENDING';
export const GET_MY_SUBSCRIPTIONS_FULFILLED = 'app/MyStuffPage/GET_MY_SUBSCRIPTIONS_FULFILLED';
export const GET_MY_SUBSCRIPTIONS_REJECTED = 'app/MyStuffPage/GET_MY_SUBSCRIPTIONS_REJECTED';

export const SUBSCRIBE_QUESTION = 'app/MyStuffPage/SUBSCRIBE_QUESTION';
export const SUBSCRIBE_QUESTION_PENDING = 'app/MyStuffPage/SUBSCRIBE_QUESTION_PENDING';
export const SUBSCRIBE_QUESTION_FULFILLED = 'app/MyStuffPage/SUBSCRIBE_QUESTION_FULFILLED';
export const SUBSCRIBE_QUESTION_REJECTED = 'app/MyStuffPage/SUBSCRIBE_QUESTION_REJECTED';
