/*
 *
 * PeerPage constants
 *
 */

export const GET_PEER_QUESTIONS = 'app/PeerPage/GET_PEER_QUESTIONS';
export const GET_PEER_QUESTIONS_FULFILLED = 'app/PeerPage/GET_PEER_QUESTIONS_FULFILLED';
export const GET_PEER_QUESTIONS_PENDING = 'app/PeerPage/GET_PEER_QUESTIONS_PENDING';
export const GET_PEER_QUESTIONS_REJECTED = 'app/PeerPage/GET_PEER_QUESTIONS_REJECTED';
