/*
 *
 * PeerPage constants
 *
 */
export const SUBMIT_NEW_PEER_QUESTION = 'app/PeerPage/SUBMIT_NEW_PEER_QUESTION';
export const SUBMIT_NEW_PEER_QUESTION_PENDING = 'app/PeerPage/SUBMIT_NEW_PEER_QUESTION_PENDING';
export const SUBMIT_NEW_PEER_QUESTION_FULFILLED = 'app/PeerPage/SUBMIT_NEW_PEER_QUESTION_FULFILLED';
export const SUBMIT_NEW_PEER_QUESTION_REJECTED = 'app/PeerPage/SUBMIT_NEW_PEER_QUESTION_REJECTED';

export const GET_PEER_QUESTIONS = 'app/PeerPage/GET_PEER_QUESTIONS';
export const GET_PEER_QUESTIONS_PENDING = 'app/PeerPage/GET_PEER_QUESTIONS_PENDING';
export const GET_PEER_QUESTIONS_FULFILLED = 'app/PeerPage/GET_PEER_QUESTIONS_FULFILLED';
export const GET_PEER_QUESTIONS_REJECTED = 'app/PeerPage/GET_PEER_QUESTIONS_REJECTED';

export const DELETE_QUESTION = 'app/PeerPage/DELETE_QUESTION';
export const DELETE_QUESTION_PENDING = 'app/PeerPage/DELETE_QUESTION_PENDING';
export const DELETE_QUESTION_FULFILLED = 'app/PeerPage/DELETE_QUESTION_FULFILLED';
export const DELETE_QUESTION_REJECTED = 'app/PeerPage/DELETE_QUESTION_REJECTED';
