/*
 *
 * StudentPage constants
 *
 */
export const SUBMIT_NEW_STUDENT_QUESTION = 'app/STUDENTPage/SUBMIT_NEW_STUDENT_QUESTION';
export const SUBMIT_NEW_STUDENT_QUESTION_PENDING = 'app/STUDENTPage/SUBMIT_NEW_STUDENT_QUESTION_PENDING';
export const SUBMIT_NEW_STUDENT_QUESTION_FULFILLED = 'app/STUDENTPage/SUBMIT_NEW_STUDENT_QUESTION_FULFILLED';
export const SUBMIT_NEW_STUDENT_QUESTION_REJECTED = 'app/STUDENTPage/SUBMIT_NEW_STUDENT_QUESTION_REJECTED';

export const GET_STUDENT_QUESTIONS = 'app/STUDENTPage/GET_STUDENT_QUESTIONS';
export const GET_STUDENT_QUESTIONS_PENDING = 'app/STUDENTPage/GET_STUDENT_QUESTIONS_PENDING';
export const GET_STUDENT_QUESTIONS_FULFILLED = 'app/STUDENTPage/GET_STUDENT_QUESTIONS_FULFILLED';
export const GET_STUDENT_QUESTIONS_REJECTED = 'app/STUDENTPage/GET_STUDENT_QUESTIONS_REJECTED';

export const SUBSCRIBE_QUESTION = 'app/STUDENTPage/SUBSCRIBE_QUESTION';
export const SUBSCRIBE_QUESTION_PENDING = 'app/STUDENTPage/SUBSCRIBE_QUESTION_PENDING';
export const SUBSCRIBE_QUESTION_FULFILLED = 'app/STUDENTPage/SUBSCRIBE_QUESTION_FULFILLED';
export const SUBSCRIBE_QUESTION_REJECTED = 'app/STUDENTPage/SUBSCRIBE_QUESTION_REJECTED';
