/*
 *
 * AlumniPage constants
 *
 */
export const SUBMIT_NEW_ALUMNI_QUESTION = 'app/ALUMNIPage/SUBMIT_NEW_ALUMNI_QUESTION';
export const SUBMIT_NEW_ALUMNI_QUESTION_PENDING = 'app/ALUMNIPage/SUBMIT_NEW_ALUMNI_QUESTION_PENDING';
export const SUBMIT_NEW_ALUMNI_QUESTION_FULFILLED = 'app/ALUMNIPage/SUBMIT_NEW_ALUMNI_QUESTION_FULFILLED';
export const SUBMIT_NEW_ALUMNI_QUESTION_REJECTED = 'app/ALUMNIPage/SUBMIT_NEW_ALUMNI_QUESTION_REJECTED';

export const GET_ALUMNI_QUESTIONS = 'app/ALUMNIPage/GET_ALUMNI_QUESTIONS';
export const GET_ALUMNI_QUESTIONS_PENDING = 'app/ALUMNIPage/GET_ALUMNI_QUESTIONS_PENDING';
export const GET_ALUMNI_QUESTIONS_FULFILLED = 'app/ALUMNIPage/GET_ALUMNI_QUESTIONS_FULFILLED';
export const GET_ALUMNI_QUESTIONS_REJECTED = 'app/ALUMNIPage/GET_ALUMNI_QUESTIONS_REJECTED';

export const SUBSCRIBE_QUESTION = 'app/ALUMNIPage/SUBSCRIBE_QUESTION';
export const SUBSCRIBE_QUESTION_PENDING = 'app/ALUMNIPage/SUBSCRIBE_QUESTION_PENDING';
export const SUBSCRIBE_QUESTION_FULFILLED = 'app/ALUMNIPage/SUBSCRIBE_QUESTION_FULFILLED';
export const SUBSCRIBE_QUESTION_REJECTED = 'app/ALUMNIPage/SUBSCRIBE_QUESTION_REJECTED';

export const GET_ALL_ALUMNI = 'app/ALUMNIPage/GET_ALL_ALUMNI';
export const GET_ALL_ALUMNI_PENDING = 'app/ALUMNIPage/GET_ALL_ALUMNI_PENDING';
export const GET_ALL_ALUMNI_FULFILLED = 'app/ALUMNIPage/GET_ALL_ALUMNI_FULFILLED';
export const GET_ALL_ALUMNI_REJECTED = 'app/ALUMNIPage/GET_ALL_ALUMNI_REJECTED';
