/*
 *
 * ProfilePage constants
 *
 */

export const GET_USER_QUESTIONS = 'app/ProfilePage/GET_USER_QUESTIONS';
export const GET_USER_QUESTIONS_FULFILLED = 'app/ProfilePage/GET_USER_QUESTIONS_FULFILLED';
export const GET_USER_QUESTIONS_PENDING = 'app/ProfilePage/GET_USER_QUESTIONS_PENDING';
export const GET_USER_QUESTIONS_REJECTED = 'app/ProfilePage/GET_USER_QUESTIONS_REJECTED';

export const GET_USER_ANSWERS = 'app/ProfilePage/GET_USER_ANSWERS';
export const GET_USER_ANSWERS_FULFILLED = 'app/ProfilePage/GET_USER_ANSWERS_FULFILLED';
export const GET_USER_ANSWERS_PENDING = 'app/ProfilePage/GET_USER_ANSWERS_PENDING';
export const GET_USER_ANSWERS_REJECTED = 'app/ProfilePage/GET_USER_ANSWERS_REJECTED';

export const GET_USER_SUBSCRIPTION = 'app/ProfilePage/GET_USER_SUBSCRIPTION';
export const GET_USER_SUBSCRIPTION_FULFILLED = 'app/ProfilePage/GET_USER_SUBSCRIPTION_FULFILLED';
export const GET_USER_SUBSCRIPTION_PENDING = 'app/ProfilePage/GET_USER_SUBSCRIPTION_PENDING';
export const GET_USER_SUBSCRIPTION_REJECTED = 'app/ProfilePage/GET_USER_SUBSCRIPTION_REJECTED';

export const GET_USER_INFO = 'app/ProfilePage/GET_USER_INFO';
export const GET_USER_INFO_FULFILLED = 'app/ProfilePage/GET_USER_INFO_FULFILLED';
export const GET_USER_INFO_PENDING = 'app/ProfilePage/GET_USER_INFO_PENDING';
export const GET_USER_INFO_REJECTED = 'app/ProfilePage/GET_USER_INFO_REJECTED';

export const CLEAR_PROFILE_PAGE = 'app/ProfilePage/CLEAR_PROFILE_PAGE';
