/*
 *
 * UserStuffPage constants
 *
 */

export const GET_USER_QUESTIONS = 'app/UserStuffPage/GET_USER_QUESTIONS';
export const GET_USER_QUESTIONS_PENDING = 'app/UserStuffPage/GET_USER_QUESTIONS_PENDING';
export const GET_USER_QUESTIONS_FULFILLED = 'app/UserStuffPage/GET_USER_QUESTIONS_FULFILLED';
export const GET_USER_QUESTIONS_REJECTED = 'app/UserStuffPage/GET_USER_QUESTIONS_REJECTED';

export const GET_USER_ANSWERS = 'app/UserStuffPage/GET_USER_ANSWERS';
export const GET_USER_ANSWERS_PENDING = 'app/UserStuffPage/GET_USER_ANSWERS_PENDING';
export const GET_USER_ANSWERS_FULFILLED = 'app/UserStuffPage/GET_USER_ANSWERS_FULFILLED';
export const GET_USER_ANSWERS_REJECTED = 'app/UserStuffPage/GET_USER_ANSWERS_REJECTED';

export const GET_USER_SUBSCRIPTIONS = 'app/UserStuffPage/GET_USER_SUBSCRIPTIONS';
export const GET_USER_SUBSCRIPTIONS_PENDING = 'app/UserStuffPage/GET_USER_SUBSCRIPTIONS_PENDING';
export const GET_USER_SUBSCRIPTIONS_FULFILLED = 'app/UserStuffPage/GET_USER_SUBSCRIPTIONS_FULFILLED';
export const GET_USER_SUBSCRIPTIONS_REJECTED = 'app/UserStuffPage/GET_USER_SUBSCRIPTIONS_REJECTED';

export const SUBSCRIBE_QUESTION = 'app/UserStuffPage/SUBSCRIBE_QUESTION';
export const SUBSCRIBE_QUESTION_PENDING = 'app/UserStuffPage/SUBSCRIBE_QUESTION_PENDING';
export const SUBSCRIBE_QUESTION_FULFILLED = 'app/UserStuffPage/SUBSCRIBE_QUESTION_FULFILLED';
export const SUBSCRIBE_QUESTION_REJECTED = 'app/UserStuffPage/SUBSCRIBE_QUESTION_REJECTED';
